#INTRO
#If you see '> # Enter on the next line', be sure the next line remains indented two spaces.

#REQUIRED
org_name: MoneroPTY
org_summary: > # Enter your summary on the next line. Be sure to indent by two spaces.
  MoneroPTY coin - Comprar y Vender Moneros
org_full_description: > # Enter your description on the next line. Be sure to indent by two spaces.
  MoneroPTY coin - Comprar y Vender Moneros Criptomonedas en Panama.

#OPTIONAL
#Non US-address support coming soon
org_general_email_inbox: info@moneropty.com
org_street_address: Panama #Please include suite number on the line below
org_address_suite: Office
org_city: Panama
org_state: CA
org_zip: > # Enter zip on next line. Be sure to indent by two spaces.
  2010
org_phone: > # Enter phone on next line. Be sure to indent by two spaces.
  (123) 456-7890

telegram_username: true
twitter_username: true
facebook_username: true
instagram_username: true
#SOCIAL MEDIA
org_telegram_username: moneropty
org_twitter_username: moneropty
org_facebook_username: moneropty
org_instagram_username: moneropty

#SEARCH ENGINES
#Changing this next setting to 'true' will allow your site to be indexed by search engines (like Google)
publish: false
cdnable: true

#THEME
#Select one of the five color schemes (default, one, two, three, or four)
theme: Four

# *** DO NOT CHANGE ANYTHING BELOW THIS LINE ***

# Unless you know what you're doing, no need to change anything below
# Build settings
baseurl: "/moneropty-web/" # the subpath of your site, e.g. /blog/
markdown: kramdown
kramdown:
  input: GFM

sass:
    sass_dir: assets/_sass
    style: compressed

#These are not yet fully supported, but should give you a head start if you know what you're doing
paypal_button_id: #Not yet available

